In [61]:
!pip install numpy pandas sckit-learn


ERROR: Could not find a version that satisfies the requirement sckit-learn (from versions: none)
ERROR: No matching distribution found for sckit-learn


In [62]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [63]:
pip install nltk

Note: you may need to restart the kernel to use updated packages.


In [64]:
!pip install matplotlib
!pip install scikit-learn
!pip install seaborn

In [67]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns
from wordcloud import WordCloud



In [68]:
pip install wordcloud 

Note: you may need to restart the kernel to use updated packages.


In [69]:
pip install stopwords


Note: you may need to restart the kernel to use updated packages.


In [73]:

# Importing necessary libraries
import numpy as np        # For numerical operations
import pandas as pd       # For data manipulation and analysis
import matplotlib.pyplot as plt  # For data visualization
%matplotlib inline
from wordcloud import WordCloud

# Importing NLTK for natural language processing
import nltk
from nltk.corpus import stopwords

In [74]:
nltk.download('stopwords')   # Downloading stopwords data
nltk.download('punkt') 

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [75]:
df=pd.read_csv("spam.csv")


In [76]:
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [77]:
df.drop(columns=["Unnamed: 2","Unnamed: 3","Unnamed: 4"],inplace=True)

In [78]:
df.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [79]:
#rename columns 
df.rename(columns={"v1":"target","v2":'text'},inplace=True)

In [80]:
df.head()

target                                               text
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [81]:
##data preprocessing
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['target'] = le.fit_transform(df["target"])



In [82]:
df.head()

target                                               text
0       0  Go until jurong point, crazy.. Available only ...
1       0                      Ok lar... Joking wif u oni...
2       1  Free entry in 2 a wkly comp to win FA Cup fina...
3       0  U dun say so early hor... U c already then say...
4       0  Nah I don't think he goes to usf, he lives aro...

In [83]:
df.duplicated().sum()

np.int64(403)

In [84]:
df=df.drop_duplicates(keep='first')
len(df)

5169

In [85]:

pip install nltk


Note: you may need to restart the kernel to use updated packages.


In [86]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [87]:
import nltk
nltk.data.path.append("C:/Users/user/nltk_data")  # Change this to your actual path
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [88]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [89]:
## feature engg
from nltk.stem import PorterStemmer
import string
ps=PorterStemmer()


In [90]:
def transform_text(text):
    # Transform the text to lowercase
    text = text.lower()
    
    # Tokenization using NLTK
    text = nltk.word_tokenize(text)
    
    # Removing special characters
    y = []
    for i in text:
        if i.isalnum():
            y.append(i)
            
    # Removing stop words and punctuation
    text = y[:]
    y.clear()
    
    # Loop through the tokens and remove stopwords and punctuation
    for i in text:
        if i not in stopwords.words('english') and i not in string.punctuation:
            y.append(i)
        
    # Stemming using Porter Stemmer
    text = y[:]
    y.clear()
    for i in text:
        y.append(ps.stem(i))
    
    # Join the processed tokens back into a single string
    return " ".join(y)


In [91]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [92]:
import nltk
print(nltk.data.path)

['C:\\Users\\user/nltk_data', 'c:\\Users\\user\\miniconda3\\nltk_data', 'c:\\Users\\user\\miniconda3\\share\\nltk_data', 'c:\\Users\\user\\miniconda3\\lib\\nltk_data', 'C:\\Users\\user\\AppData\\Roaming\\nltk_data', 'C:\\nltk_data', 'D:\\nltk_data', 'E:\\nltk_data', 'C:/Users/user/nltk_data', 'C:/Users/user/nltk_data', 'D:\\nltk_data', 'C:/Users/user/nltk_data']


In [93]:
nltk.data.path.append("C:/Users/user/nltk_data")


In [94]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [97]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.


True

In [98]:
transform_text('Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...')


'go jurong point crazi avail bugi n great world la e buffet cine got amor wat'

In [99]:
df['transformed_text'] = df['text'].apply(transform_text)
df.head()


target                                               text  \
0       0  Go until jurong point, crazy.. Available only ...   
1       0                      Ok lar... Joking wif u oni...   
2       1  Free entry in 2 a wkly comp to win FA Cup fina...   
3       0  U dun say so early hor... U c already then say...   
4       0  Nah I don't think he goes to usf, he lives aro...   

                                    transformed_text  
0  go jurong point crazi avail bugi n great world...  
1                              ok lar joke wif u oni  
2  free entri 2 wkli comp win fa cup final tkt 21...  
3                u dun say earli hor u c alreadi say  
4               nah think goe usf live around though

In [100]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
tfidf=TfidfVectorizer(max_features=500)


In [107]:
X = tfidf.fit_transform(df['transformed_text']).toarray()
y = df['target'].values

In [108]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [104]:
pip install xgboost


   ---------------------------------------- 0.0/150.0 MB ? eta -:--:--
   ---------------------------------------- 1.6/150.0 MB 12.0 MB/s eta 0:00:13
   - -------------------------------------- 5.0/150.0 MB 14.4 MB/s eta 0:00:11
   - -------------------------------------- 7.3/150.0 MB 12.9 MB/s eta 0:00:12
   -- ------------------------------------- 9.7/150.0 MB 12.3 MB/s eta 0:00:12
   --- ------------------------------------ 11.3/150.0 MB 11.4 MB/s eta 0:00:13
   --- ------------------------------------ 12.3/150.0 MB 10.3 MB/s eta 0:00:14
   --- ------------------------------------ 12.8/150.0 MB 10.1 MB/s eta 0:00:14
   --- ------------------------------------ 14.4/150.0 MB 8.8 MB/s eta 0:00:16
   ---- ----------------------------------- 15.7/150.0 MB 8.5 MB/s eta 0:00:16
   ---- ----------------------------------- 17.0/150.0 MB 8.3 MB/s eta 0:00:17
   ----- ---------------------------------- 18.9/150.0 MB 8.3 MB/s eta 0:00:16
   ----- ---------------------------------- 19.9/150.0 MB

In [105]:
##model training 
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC 
from sklearn.naive_bayes import GaussianNB,MultinomialNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier,AdaBoostClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score,confusion_matrix,classification_report

In [109]:
knc = KNeighborsClassifier()
knc.fit(X_train,y_train)
y_pred = knc.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9294003868471954
[[887   2]
 [ 71  74]]
              precision    recall  f1-score   support

           0       0.93      1.00      0.96       889
           1       0.97      0.51      0.67       145

    accuracy                           0.93      1034
   macro avg       0.95      0.75      0.82      1034
weighted avg       0.93      0.93      0.92      1034



In [110]:
mnb = MultinomialNB()
mnb.fit(X_train,y_train)
y_pred = mnb.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9758220502901354
[[887   2]
 [ 23 122]]
              precision    recall  f1-score   support

           0       0.97      1.00      0.99       889
           1       0.98      0.84      0.91       145

    accuracy                           0.98      1034
   macro avg       0.98      0.92      0.95      1034
weighted avg       0.98      0.98      0.98      1034



In [111]:
dtc = DecisionTreeClassifier(max_depth = 5)
dtc.fit(X_train,y_train)
y_pred=dtc.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9313346228239845
[[870  19]
 [ 52  93]]
              precision    recall  f1-score   support

           0       0.94      0.98      0.96       889
           1       0.83      0.64      0.72       145

    accuracy                           0.93      1034
   macro avg       0.89      0.81      0.84      1034
weighted avg       0.93      0.93      0.93      1034



In [112]:
rfc = RandomForestClassifier(n_estimators = 50, random_state=2)
rfc.fit(X_train,y_train)
y_pred = rfc.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.971953578336557
[[885   4]
 [ 25 120]]


In [113]:
abc = AdaBoostClassifier(n_estimators = 50, random_state = 2)
abc.fit(X_train,y_train)
y_pred = abc.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9129593810444874
[[869  20]
 [ 70  75]]
              precision    recall  f1-score   support

           0       0.93      0.98      0.95       889
           1       0.79      0.52      0.62       145

    accuracy                           0.91      1034
   macro avg       0.86      0.75      0.79      1034
weighted avg       0.91      0.91      0.91      1034



In [114]:
bc = BaggingClassifier(n_estimators = 50, random_state = 2)
bc.fit(X_train,y_train)
y_pred = bc.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9584139264990329
[[871  18]
 [ 25 120]]
              precision    recall  f1-score   support

           0       0.97      0.98      0.98       889
           1       0.87      0.83      0.85       145

    accuracy                           0.96      1034
   macro avg       0.92      0.90      0.91      1034
weighted avg       0.96      0.96      0.96      1034



In [115]:
etc = ExtraTreesClassifier(n_estimators = 50, random_state = 2)
etc.fit(X_train,y_train)
y_pred = etc.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report)

0.9777562862669246
[[881   8]
 [ 15 130]]
<function classification_report at 0x00000235AAB47D80>


In [116]:
gbdt = GradientBoostingClassifier(n_estimators = 50, random_state = 2)    
gbdt.fit(X_train,y_train)
y_pred = gbdt.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9516441005802708
[[884   5]
 [ 45 100]]
              precision    recall  f1-score   support

           0       0.95      0.99      0.97       889
           1       0.95      0.69      0.80       145

    accuracy                           0.95      1034
   macro avg       0.95      0.84      0.89      1034
weighted avg       0.95      0.95      0.95      1034



In [117]:
xgb  = XGBClassifier(n_estimators = 50, random_state = 2)
xgb.fit(X_train,y_train)
y_pred = xgb.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9680851063829787
[[882   7]
 [ 26 119]]
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       889
           1       0.94      0.82      0.88       145

    accuracy                           0.97      1034
   macro avg       0.96      0.91      0.93      1034
weighted avg       0.97      0.97      0.97      1034

